/////////////////////////////////////////////////YAWN Setlist/////////////////////////////////////////////////

(
~setList = Dictionary.with(*[

	0 -> (
		song: "numberThree"
	),

	1 -> (
		song: "numberOne"
	),

	2 -> (
		song: "numberTwo"
	),

	3 -> (
		song: "numberFour"
	),

	4 -> (
		song: "empty"
	),

	5 -> (
		song: "empty"
	),

	6 -> (
		song: "empty"
	),

	7 -> (
		song: "empty"
	),

]);

"setlist loaded".postln;

);
